### ISSUE TITLE
Send a Solana Transaction Javascript-SDK 

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/Solana-Compliance#10]
[Issue in Solana Forum](https://forums.solana.com/t/send-a-solana-transaction-javascript-sdk/8614)

```
const solanaWeb3 = require('@solana/web3.js');
console.log(solanaWeb3);

const {Keypair, Transaction, SystemProgram, LAMPORTS_PER_SOL} = require("@solana/web3.js");

let transaction = new Transaction();

transaction.add(
  SystemProgram.transfer({
    fromPubkey: fromKeypair.publicKey,
    toPubkey: toKeypair.publicKey,
    lamports: LAMPORTS_PER_SOL
  })
);
```

The two main issues are appropriately defining the `fromPubkey` and `toPubkey` variables to be interpreted by the blockchain and how to deploy the script to the Solana TestNet.

**Comment by terrykeng** [comment]
# Solved
Currently I don’t have access to my developing computer but I can provide you with a link and any other assistance 
Click this link to get started [here](https://www.quicknode.com/guides/web3-sdks/how-to-send-a-transaction-on-solana-using-javascript) 
This code 
```const solanaWeb3 = require('@solana/web3.js');
console.log(solanaWeb3);

const {Keypair, Transaction, SystemProgram, LAMPORTS_PER_SOL} = require("@solana/web3.js");

let transaction = new Transaction();

transaction.add(
  SystemProgram.transfer({
    fromPubkey: fromKeypair.publicKey,
    toPubkey: toKeypair.publicKey,
    lamports: LAMPORTS_PER_SOL
  })
);
``` 
is incomplete 
adding `const  fromkeypair = web3.Keypair.generate();` creates a key pair more like a private key in algorand, and `fromPubkey` converts that private key to an address using whatever encoding system solana uses
Same thing can be done for `toPubkey`
If you want to see the address adding `console.log(fromPubkey);`
`console.log(toPubkey);` would do that.
For the running steps just follow the steps in the link above and it would work just fine, you can also use the source code on the link to make your own first transaction but remember changing the devnet to testnet for testnet transactions, and also you can make all these transactions using your terminal alone, solana made developing a bit harder or algorand made it a lot easier one of those statements are true but to make transactions easily using your terminal you can use this link [here](https://docs.solana.com/cli) it is really explained here and it’s easy to implement and you’ll understand it a lot better .
Once again I don’t have access to my developing computer right now but I’m happy to help solve this problem cause it was basically what I was battling all day.

**Comment by terrykeng** [comment]
I just got access to my computer and as promised I cooked up a step by step tutorial to help you make the transactions you want how you want it. Kindly check my [repo](https://github.com/terrykeng/sol-web3-js). All the run and configuration steps are there and if you still have problems understanding it click this [link](https://www.quicknode.com/guides/web3-sdks/how-to-send-a-transaction-on-solana-using-javascript) for more detailed information.
Thank You.

**Comment by Bhaney44** [comment]
Can you make a pr for this [here](https://github.com/ChoiceCoin/Solana). Make sure to add your files, the readme and the transaction file to a new folder called `transfer`. Once you do this I will test the code on my machine. And let you know bugs or make award. Thank you!

**Comment by ChoiceCoin** [comment]
> # Solved
> Currently I don’t have access to my developing computer but I can provide you with a link and any other assistance Click this link to get started [here](https://www.quicknode.com/guides/web3-sdks/how-to-send-a-transaction-on-solana-using-javascript) This code
> 
> ```
> console.log(solanaWeb3);
> 
> const {Keypair, Transaction, SystemProgram, LAMPORTS_PER_SOL} = require("@solana/web3.js");
> 
> let transaction = new Transaction();
> 
> transaction.add(
>   SystemProgram.transfer({
>     fromPubkey: fromKeypair.publicKey,
>     toPubkey: toKeypair.publicKey,
>     lamports: LAMPORTS_PER_SOL
>   })
> );
> ```
> 
> is incomplete adding `const fromkeypair = web3.Keypair.generate();` creates a key pair more like a private key in algorand, and `fromPubkey` converts that private key to an address using whatever encoding system solana uses Same thing can be done for `toPubkey` If you want to see the address adding `console.log(fromPubkey);` `console.log(toPubkey);` would do that. For the running steps just follow the steps in the link above and it would work just fine, you can also use the source code on the link to make your own first transaction but remember changing the devnet to testnet for testnet transactions, and also you can make all these transactions using your terminal alone, solana made developing a bit harder or algorand made it a lot easier one of those statements are true but to make transactions easily using your terminal you can use this link [here](https://docs.solana.com/cli) it is really explained here and it’s easy to implement and you’ll understand it a lot better . Once again I don’t have access to my developing computer right now but I’m happy to help solve this problem cause it was basically what I was battling all day.

This is not solved yet.

**Comment by ChoiceCoin** [comment]
Solution

```
const web3 =  require("@solana/web3.js");

(async () => {
  // Connect to cluster
  console.log(web3.clusterApiUrl('devnet'))
  const connection = new web3.Connection(
    web3.clusterApiUrl('devnet'),
    'confirmed',
  );
  // Uncomment the below command to test your connection to your node
  //console.log(await connection.getEpochInfo())

  // Using the secretkey to generate the keypair
  const secretkey = Uint8Array.from(['']);  

  //If you already have enough test sol in your account you can comment this out
  const airdropSignature = await connection.requestAirdrop(
    from.publicKey,
    web3.LAMPORTS_PER_SOL,
  );
  await connection.confirmTransaction(airdropSignature);

  // Add transfer instruction to transaction
  const transaction = new web3.Transaction().add(
    web3.SystemProgram.transfer({
      fromPubkey: from.publicKey,
      toPubkey: '',
      lamports: web3.LAMPORTS_PER_SOL / 100,
    }),
  );

  // Sign transaction, broadcast, and confirm
  const signature = await web3.sendAndConfirmTransaction(
    connection,
    transaction,
    [from],
  );
  console.log('SIGNATURE', signature);
})();

// SIGNATURE 36bvGs1ddyfYJeGudoDKm4fFW7HgULWKRz7vGgWjv3g33NsvQMgKyu9Mb9eGc8VuetVd2BVTyUVt7TeVU8j5dJ6V
```
